COMMIT_MESSAGE = "Bump podspec to"

lane :tests do
  scan(workspace: "Example/gitlabclient.xcworkspace", scheme: "gitlabclient-Example", clean: true)
end

lane :ci do
  tests
end

lane :push do
  version = version_bump_podspec(path: "gitlabclient.podspec")
  git_commit(path: ["./gitlabclient.podspec", "./Example/Podfile.lock"], message: "#{COMMIT_MESSAGE} #{version}")
  sh("git fetch --tags")
  sh("git tag #{version}")
  push_to_git_remote(remote_branch: 'master', force: false, tags: true)
  pod_push(allow_warnings: true, verbose: true)
end
