COMMIT_MESSAGE = "Bump podspec to"

lane :tests do
  scan(workspace: "Example/gitlabclient.xcworkspace", scheme: "gitlabclient-Example", clean: true)
end

lane :ci do
  tests
end

lane :push do
  version = version_bump_podspec(path: "gitlabclient.podspec")
  git_commit(path: ["./gitlabclient.podspec", "./Example/Podfile.lock"], message: "#{COMMIT_MESSAGE} #{version}")
  sh("git fetch --tags")
  sh("git tag #{version}")
  gl_token = ENV["GL_TOKEN"]
  sh("git remote set-url origin 'git@gitlab.com:caramba/gitlabclient.git'")
  sh("git push origin HEAD:master --tags")
  pod_push(allow_warnings: true, verbose: true)
end
